import type {
  ExecutionRecord,
  Integration,
  Issue,
  Repository,
  Severity,
} from "@/types";

export const repositories: Repository[] = [
  {
    id: "r1",
    owner: "northwind",
    name: "backend-api",
    fullName: "northwind/backend-api",
    visibility: "private",
    openIssues: 17,
    language: "TypeScript",
  },
  {
    id: "r2",
    owner: "northwind",
    name: "payments-service",
    fullName: "northwind/payments-service",
    visibility: "private",
    openIssues: 9,
    language: "Go",
  },
  {
    id: "r3",
    owner: "northwind",
    name: "web-console",
    fullName: "northwind/web-console",
    visibility: "private",
    openIssues: 24,
    language: "TypeScript",
  },
  {
    id: "r4",
    owner: "northwind",
    name: "data-pipeline",
    fullName: "northwind/data-pipeline",
    visibility: "public",
    openIssues: 6,
    language: "Python",
  },
];

const mk = (
  number: number,
  title: string,
  labels: string[],
  severity: Severity,
  priority: Severity,
  createdAt: string,
  assignee: string | null,
  recommendation: string,
  analysis: Issue["analysis"],
  status: Issue["status"] = "open",
): Issue => ({
  id: `i-${number}`,
  number,
  title,
  labels,
  status,
  severity,
  priority,
  createdAt,
  assignee,
  recommendation,
  analysis,
});

export const issues: Issue[] = [
  mk(
    142,
    "Payment checkout fails after successful authentication",
    ["bug", "payment"],
    "critical",
    "critical",
    "2026-09-21",
    "m.alvarez",
    "Immediate action required",
    {
      summary:
        "Checkout requests return 500 after the auth callback resolves, blocking card and wallet payments in production.",
      impact: "high",
      confidence: 94,
      whyItMatters: "Users cannot complete purchases — direct revenue loss.",
      recommendedAction: "Create Jira task and notify the payment team.",
    },
  ),
  mk(
    137,
    "Authentication timeout on refresh token rotation",
    ["bug", "auth", "regression"],
    "critical",
    "high",
    "2026-09-20",
    "j.okafor",
    "Immediate action required",
    {
      summary:
        "Refresh token rotation exceeds the 5s gateway timeout under load, logging users out mid-session.",
      impact: "high",
      confidence: 91,
      whyItMatters: "Active sessions drop during peak traffic windows.",
      recommendedAction: "Create Jira task and notify the platform team.",
    },
  ),
  mk(
    128,
    "Invoice generation failure for annual plans",
    ["bug", "billing"],
    "critical",
    "high",
    "2026-09-18",
    null,
    "Escalate to billing owner",
    {
      summary:
        "Annual invoices fail to render when a proration line item is present, leaving accounts unbilled.",
      impact: "high",
      confidence: 88,
      whyItMatters: "Revenue recognition is delayed for annual customers.",
      recommendedAction: "Create Jira task and monitor the retry queue.",
    },
  ),
  mk(
    121,
    "Webhook retries duplicate order events",
    ["bug", "integrations"],
    "high",
    "high",
    "2026-09-17",
    "s.patel",
    "Schedule for current sprint",
    {
      summary: "Retry logic lacks idempotency keys, producing duplicate downstream orders.",
      impact: "medium",
      confidence: 83,
      whyItMatters: "Partners receive duplicate fulfilment requests.",
      recommendedAction: "Create Jira task for the integrations squad.",
    },
  ),
  mk(
    118,
    "Search index lags behind writes by up to 4 minutes",
    ["bug", "search", "performance"],
    "high",
    "medium",
    "2026-09-16",
    "l.zhang",
    "Schedule for current sprint",
    {
      summary: "Indexer batching window is too wide during bulk imports.",
      impact: "medium",
      confidence: 79,
      whyItMatters: "Users see stale results right after editing records.",
      recommendedAction: "Monitor and tune the batch window.",
    },
  ),
  mk(
    115,
    "Rate limiter returns 500 instead of 429",
    ["bug", "api"],
    "high",
    "medium",
    "2026-09-15",
    null,
    "Schedule for current sprint",
    {
      summary: "Limiter middleware throws when Redis is briefly unavailable.",
      impact: "medium",
      confidence: 86,
      whyItMatters: "Clients cannot back off correctly on throttling.",
      recommendedAction: "Create Jira task for the API platform team.",
    },
  ),
  mk(
    111,
    "CSV export truncates rows above 50k",
    ["bug", "reports"],
    "high",
    "medium",
    "2026-09-14",
    "d.nguyen",
    "Plan for next sprint",
    {
      summary: "Streaming writer closes early because of an unawaited flush.",
      impact: "medium",
      confidence: 81,
      whyItMatters: "Finance reports are silently incomplete.",
      recommendedAction: "Create Jira task and add a regression test.",
    },
  ),
  mk(
    108,
    "Stale cache after tenant settings update",
    ["bug", "cache"],
    "high",
    "low",
    "2026-09-13",
    null,
    "Monitor",
    {
      summary: "Tenant settings cache key omits the region suffix.",
      impact: "low",
      confidence: 74,
      whyItMatters: "Settings changes take up to 10 minutes to apply.",
      recommendedAction: "Monitor, no immediate action.",
    },
  ),
  mk(
    104,
    "Email notifications missing localized subjects",
    ["bug", "i18n"],
    "medium",
    "medium",
    "2026-09-12",
    "a.karim",
    "Plan for next sprint",
    {
      summary: "Subject templates fall back to English for de-DE and fr-FR.",
      impact: "low",
      confidence: 77,
      whyItMatters: "Localized customers receive mixed-language email.",
      recommendedAction: "Backlog for the growth squad.",
    },
  ),
  mk(
    99,
    "Pagination cursor breaks on deleted records",
    ["bug", "api"],
    "medium",
    "medium",
    "2026-09-11",
    null,
    "Plan for next sprint",
    {
      summary: "Cursor decoding fails when the anchor row is soft-deleted.",
      impact: "medium",
      confidence: 72,
      whyItMatters: "Clients paging large lists hit an occasional dead end.",
      recommendedAction: "Backlog with a reproduction test.",
    },
  ),
  mk(
    95,
    "Audit log timestamps stored without timezone",
    ["bug", "audit"],
    "medium",
    "low",
    "2026-09-10",
    "m.alvarez",
    "Monitor",
    {
      summary: "Timestamps persist as naive local time on one worker pool.",
      impact: "low",
      confidence: 69,
      whyItMatters: "Audit exports are off by hours for EU tenants.",
      recommendedAction: "Monitor, no immediate action.",
    },
  ),
  mk(
    92,
    "Retry banner flickers on slow networks",
    ["bug", "ui"],
    "medium",
    "low",
    "2026-09-09",
    null,
    "Monitor",
    {
      summary: "Banner mounts before the request debounce settles.",
      impact: "low",
      confidence: 65,
      whyItMatters: "Minor visual noise during recovery.",
      recommendedAction: "Backlog.",
    },
  ),
  mk(
    88,
    "Sorting by owner ignores case",
    ["bug", "ui"],
    "medium",
    "low",
    "2026-09-08",
    "s.patel",
    "Monitor",
    {
      summary: "Comparator uses byte order instead of locale collation.",
      impact: "low",
      confidence: 63,
      whyItMatters: "List order looks arbitrary to users.",
      recommendedAction: "Backlog.",
    },
  ),
  mk(
    84,
    "Docs link in error toast points to old path",
    ["bug", "docs"],
    "medium",
    "low",
    "2026-09-07",
    null,
    "Monitor",
    {
      summary: "Toast references a docs route removed in the last migration.",
      impact: "low",
      confidence: 92,
      whyItMatters: "Users land on a 404 while troubleshooting.",
      recommendedAction: "Quick fix, no escalation.",
    },
  ),
  mk(
    80,
    "Avatar upload rejects HEIC files",
    ["bug", "uploads"],
    "low",
    "low",
    "2026-09-06",
    "l.zhang",
    "Backlog",
    {
      summary: "MIME allowlist omits image/heic.",
      impact: "low",
      confidence: 70,
      whyItMatters: "Some mobile users cannot set an avatar.",
      recommendedAction: "Backlog.",
    },
  ),
  mk(
    76,
    "Tooltip clipped inside scrollable table",
    ["bug", "ui"],
    "low",
    "low",
    "2026-09-05",
    null,
    "Backlog",
    {
      summary: "Overflow container clips the floating layer.",
      impact: "low",
      confidence: 61,
      whyItMatters: "Truncated labels are hard to read.",
      recommendedAction: "Backlog.",
    },
  ),
  mk(
    71,
    "Duplicate log line on graceful shutdown",
    ["bug", "observability"],
    "low",
    "low",
    "2026-09-04",
    null,
    "Backlog",
    {
      summary: "Shutdown hook registered twice in the worker entrypoint.",
      impact: "low",
      confidence: 58,
      whyItMatters: "Slightly noisier logs, no functional impact.",
      recommendedAction: "Backlog.",
    },
  ),
];

export const integrations: Integration[] = [
  {
    id: "github",
    name: "GitHub",
    description: "Issue discovery and repository context",
    status: "connected",
    detail: "northwind org · 4 repositories",
  },
  {
    id: "jira",
    name: "Jira",
    description: "Task creation and tracking",
    status: "connected",
    detail: "Project BUG · Cloud site northwind",
  },
  {
    id: "slack",
    name: "Slack",
    description: "Team notifications",
    status: "connected",
    detail: "Workspace northwind · 3 channels",
  },
  {
    id: "openai",
    name: "OpenAI",
    description: "Reasoning and bug classification",
    status: "connected",
    detail: "Model gpt-class reasoning tier",
  },
  {
    id: "swytchcode",
    name: "Swytchcode",
    description: "Tool routing and API execution layer",
    status: "connected",
    detail: "5 tool schemas registered",
  },
];

export const executionHistory: ExecutionRecord[] = [
  {
    id: "run-0912",
    prompt: "Analyze open bugs and create Jira tasks for critical issues.",
    repository: "northwind/backend-api",
    startedAt: "2026-09-25 16:04",
    durationMs: 14200,
    status: "completed",
    analyzed: 17,
    jiraCreated: 3,
    slackSent: 3,
  },
  {
    id: "run-0911",
    prompt: "Find high-priority bugs and notify the team on Slack.",
    repository: "northwind/web-console",
    startedAt: "2026-09-24 11:31",
    durationMs: 11800,
    status: "completed",
    analyzed: 24,
    jiraCreated: 2,
    slackSent: 2,
  },
  {
    id: "run-0910",
    prompt: "Review unresolved bugs and recommend immediate attention items.",
    repository: "northwind/payments-service",
    startedAt: "2026-09-23 09:12",
    durationMs: 9400,
    status: "failed",
    analyzed: 9,
    jiraCreated: 0,
    slackSent: 0,
  },
];
