/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BugAnalysisRouteImport } from './routes/bug-analysis'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as JiraTasksRouteImport } from './routes/jira-tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SlackActivityRouteImport } from './routes/slack-activity'
import { Route as WorkflowRouteImport } from './routes/workflow'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BugAnalysisRoute = BugAnalysisRouteImport.update({
  id: '/bug-analysis',
  path: '/bug-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const JiraTasksRoute = JiraTasksRouteImport.update({
  id: '/jira-tasks',
  path: '/jira-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SlackActivityRoute = SlackActivityRouteImport.update({
  id: '/slack-activity',
  path: '/slack-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bug-analysis': typeof BugAnalysisRoute
  '/history': typeof HistoryRoute
  '/integrations': typeof IntegrationsRoute
  '/jira-tasks': typeof JiraTasksRoute
  '/settings': typeof SettingsRoute
  '/slack-activity': typeof SlackActivityRoute
  '/workflow': typeof WorkflowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bug-analysis': typeof BugAnalysisRoute
  '/history': typeof HistoryRoute
  '/integrations': typeof IntegrationsRoute
  '/jira-tasks': typeof JiraTasksRoute
  '/settings': typeof SettingsRoute
  '/slack-activity': typeof SlackActivityRoute
  '/workflow': typeof WorkflowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bug-analysis': typeof BugAnalysisRoute
  '/history': typeof HistoryRoute
  '/integrations': typeof IntegrationsRoute
  '/jira-tasks': typeof JiraTasksRoute
  '/settings': typeof SettingsRoute
  '/slack-activity': typeof SlackActivityRoute
  '/workflow': typeof WorkflowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bug-analysis'
    | '/history'
    | '/integrations'
    | '/jira-tasks'
    | '/settings'
    | '/slack-activity'
    | '/workflow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bug-analysis'
    | '/history'
    | '/integrations'
    | '/jira-tasks'
    | '/settings'
    | '/slack-activity'
    | '/workflow'
  id:
    | '__root__'
    | '/'
    | '/bug-analysis'
    | '/history'
    | '/integrations'
    | '/jira-tasks'
    | '/settings'
    | '/slack-activity'
    | '/workflow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BugAnalysisRoute: typeof BugAnalysisRoute
  HistoryRoute: typeof HistoryRoute
  IntegrationsRoute: typeof IntegrationsRoute
  JiraTasksRoute: typeof JiraTasksRoute
  SettingsRoute: typeof SettingsRoute
  SlackActivityRoute: typeof SlackActivityRoute
  WorkflowRoute: typeof WorkflowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bug-analysis': {
      id: '/bug-analysis'
      path: '/bug-analysis'
      fullPath: '/bug-analysis'
      preLoaderRoute: typeof BugAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jira-tasks': {
      id: '/jira-tasks'
      path: '/jira-tasks'
      fullPath: '/jira-tasks'
      preLoaderRoute: typeof JiraTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slack-activity': {
      id: '/slack-activity'
      path: '/slack-activity'
      fullPath: '/slack-activity'
      preLoaderRoute: typeof SlackActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BugAnalysisRoute: BugAnalysisRoute,
  HistoryRoute: HistoryRoute,
  IntegrationsRoute: IntegrationsRoute,
  JiraTasksRoute: JiraTasksRoute,
  SettingsRoute: SettingsRoute,
  SlackActivityRoute: SlackActivityRoute,
  WorkflowRoute: WorkflowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
